<?php

/**
 * DmTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lantenora
 * @subpackage model
 * @author     thibault d
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
class DmTag extends PluginDmTag
{
}
