generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Commentaire
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: commentaire
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - =auteur
          - image_id
          - texte
          - is_active
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
      filter:
        display:
          - id
          - image_id
          - auteur
          - texte
      form:
        display:
          NONE: [auteur, image_id]
          Texte: [texte]
        class: CommentaireAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: false
