<?php

/**
 * Commentaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lantenora
 * @subpackage model
 * @author     thibault d <you@email.com>
 * @version    SVN: $Id: Builder.php 5925 2009-06-22 21:27:17Z jwage $
 */
class Commentaire extends BaseCommentaire
{
  
  public function __toString()
  {
    return $this->_get('auteur') ? $this->_get('auteur') : 'anonyme';
  }
  
}