<?php

/**
 * Image
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lantenora
 * @subpackage model
 * @author     thibault d <you@email.com>
 * @version    SVN: $Id: Builder.php 5925 2009-06-22 21:27:17Z jwage $
 */
class Image extends BaseImage
{

  public function getAuteurPage()
  {
    return dmDb::query('DmPage p')
    ->where('p.module = ?', 'auteur')
    ->andWhere('p.action = ?', 'show')
    ->andWhere('p.record_id = ?', $this->user_id)
    ->withI18n()
    ->fetchOne();
  }
  
}