<?php

/**
 * Invite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blancerf2
 * @subpackage model
 * @author     thibault d
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Invite extends BaseInvite
{
}
