<?php

/**
 * LienType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blancerf2
 * @subpackage model
 * @author     thibault d
 * @version    SVN: $Id: Builder.php 6508 2009-10-14 06:28:49Z jwage $
 */
class LienType extends BaseLienType
{
}
