<?php

/**
 * Rubrique
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lantenora
 * @subpackage model
 * @author     thibault d <you@email.com>
 * @version    SVN: $Id: Builder.php 5925 2009-06-22 21:27:17Z jwage $
 */
class Rubrique extends BaseRubrique
{
  public function preSave($event)
  {
    if(array_key_exists('is_active', $this->getModified()))
    {
      foreach($this->get('Images') as $image)
      {
        $image->set('is_active', $this->get('is_active'));
      }

      $this->get('Images')->save();
    }

    return parent::preSave($event);
  }
}