<?php

/**
 * Tag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lantenora
 * @subpackage model
 * @author     thibault d <you@email.com>
 * @version    SVN: $Id: Builder.php 5925 2009-06-22 21:27:17Z jwage $
 */
class Tag extends BaseTag
{
  
  public function preSave($event)
  {
    $this->nom = trim(str_replace(',', ' ', $this->nom));
    $this->strip = dmString::slugify($this->nom);
    
    parent::preSave($event);
  }
}