generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Preface
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: preface
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        is_active:
          label: Active
      list:
        display:
          - '=nom'
          - rubrique_id
          - image_id
          - description
          - is_active
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - nom
          - is_active
          - rubrique_id
          - description
          - image_id
          - created_at
          - updated_at
      form:
        display:
          NONE: [nom, is_active, rubrique_id]
          Image: [image_id_form, image_id_view]
          Description: [description]
        class: PrefaceAdminForm
        fields: {  }
      edit: ~
      new: ~
