<?php

/**
 * DmLock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lantenora
 * @subpackage model
 * @author     thibault d
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
class DmLock extends PluginDmLock
{
}
