default:
  http_metas:
    content-type: text/html

  metas:

  stylesheets:
    - layout
    - main
    - markdown
    - title
    - rubrique
    - image
    - tag
    - commentaire
    - lien
    - auteur

  javascripts:
    - front
    - image

  has_layout:     true
  layout:         layout