default:
  http_metas:
    content-type: text/html

  metas:

  stylesheets:
    - lib.reset
    - layout
    - main
    - markdown
    - title
    - rubrique
    - image
    - tag
    - commentaire
    - lien
    - auteur

  javascripts:
    - lib.ui-core
    - lib.ui-widget
    - image
    - front

  has_layout:     true
  layout:         layout