<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('image', 'image_user_id_dm_user_id');
        $this->dropForeignKey('image', 'image_media_id_dm_media_id');
        $this->dropForeignKey('image', 'image_rubrique_id_rubrique_id');
        $this->dropForeignKey('lien', 'lien_lien_type_id_lien_type_id');
        $this->createForeignKey('image', 'image_user_id_dm_user_id_1', array(
             'name' => 'image_user_id_dm_user_id_1',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_user',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('image', 'image_media_id_dm_media_id_1', array(
             'name' => 'image_media_id_dm_media_id_1',
             'local' => 'media_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('image', 'image_rubrique_id_rubrique_id_1', array(
             'name' => 'image_rubrique_id_rubrique_id_1',
             'local' => 'rubrique_id',
             'foreign' => 'id',
             'foreignTable' => 'rubrique',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('lien', 'lien_lien_type_id_lien_type_id_1', array(
             'name' => 'lien_lien_type_id_lien_type_id_1',
             'local' => 'lien_type_id',
             'foreign' => 'id',
             'foreignTable' => 'lien_type',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->addIndex('image', 'image_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('image', 'image_media_id', array(
             'fields' => 
             array(
              0 => 'media_id',
             ),
             ));
        $this->addIndex('image', 'image_rubrique_id', array(
             'fields' => 
             array(
              0 => 'rubrique_id',
             ),
             ));
        $this->addIndex('lien', 'lien_lien_type_id', array(
             'fields' => 
             array(
              0 => 'lien_type_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('image', 'image_user_id_dm_user_id', array(
             'name' => 'image_user_id_dm_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('image', 'image_media_id_dm_media_id', array(
             'name' => 'image_media_id_dm_media_id',
             'local' => 'media_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('image', 'image_rubrique_id_rubrique_id', array(
             'name' => 'image_rubrique_id_rubrique_id',
             'local' => 'rubrique_id',
             'foreign' => 'id',
             'foreignTable' => 'rubrique',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('lien', 'lien_lien_type_id_lien_type_id', array(
             'name' => 'lien_lien_type_id_lien_type_id',
             'local' => 'lien_type_id',
             'foreign' => 'id',
             'foreignTable' => 'lien_type',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->dropForeignKey('image', 'image_user_id_dm_user_id_1');
        $this->dropForeignKey('image', 'image_media_id_dm_media_id_1');
        $this->dropForeignKey('image', 'image_rubrique_id_rubrique_id_1');
        $this->dropForeignKey('lien', 'lien_lien_type_id_lien_type_id_1');
        $this->removeIndex('image', 'image_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('image', 'image_media_id', array(
             'fields' => 
             array(
              0 => 'media_id',
             ),
             ));
        $this->removeIndex('image', 'image_rubrique_id', array(
             'fields' => 
             array(
              0 => 'rubrique_id',
             ),
             ));
        $this->removeIndex('lien', 'lien_lien_type_id', array(
             'fields' => 
             array(
              0 => 'lien_type_id',
             ),
             ));
    }
}