<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('dm_lock', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'user_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'module' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '127',
             ),
             'action' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '127',
             ),
             'record_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '1',
              'default' => '0',
              'length' => '8',
             ),
             'time' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'app' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '127',
             ),
             'url' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'culture' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '15',
             ),
             ), array(
             'indexes' => 
             array(
              'dmLockIndex' => 
              array(
              'fields' => 
              array(
               0 => 'user_id',
               1 => 'module',
               2 => 'action',
               3 => 'record_id',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('dm_auto_seo_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'h1' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'keywords' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'strip_words' => 
             array(
              'type' => 'string',
              'length' => '10000',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('dm_mail_template_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '5000',
             ),
             'subject' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '5000',
             ),
             'body' => 
             array(
              'type' => 'clob',
              'notnull' => '1',
              'length' => '',
             ),
             'from_email' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '5000',
             ),
             'to_email' => 
             array(
              'type' => 'string',
              'length' => '5000',
             ),
             'is_html' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '0',
              'length' => '25',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '1',
              'length' => '25',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('dm_widget_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'value' => 
             array(
              'type' => 'string',
              'length' => '60000',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('dm_auto_seo', 'slug');
        $this->removeColumn('dm_auto_seo', 'name');
        $this->removeColumn('dm_auto_seo', 'title');
        $this->removeColumn('dm_auto_seo', 'h1');
        $this->removeColumn('dm_auto_seo', 'description');
        $this->removeColumn('dm_auto_seo', 'keywords');
        $this->removeColumn('dm_auto_seo', 'strip_words');
        $this->removeColumn('dm_error', 'klass');
        $this->removeColumn('dm_group_permission', 'created_at');
        $this->removeColumn('dm_group_permission', 'updated_at');
        $this->removeColumn('dm_mail_template', 'description');
        $this->removeColumn('dm_mail_template', 'title');
        $this->removeColumn('dm_mail_template', 'body');
        $this->removeColumn('dm_mail_template', 'from_email');
        $this->removeColumn('dm_mail_template', 'to_email');
        $this->removeColumn('dm_mail_template', 'is_html');
        $this->removeColumn('dm_mail_template', 'is_active');
        $this->removeColumn('dm_page', 'is_secure');
        $this->removeColumn('dm_remember_key', 'updated_at');
        $this->removeColumn('dm_sent_mail', 'name');
        $this->removeColumn('dm_sent_mail', 'header');
        $this->removeColumn('dm_sent_mail', 'description');
        $this->removeColumn('dm_user_group', 'created_at');
        $this->removeColumn('dm_user_group', 'updated_at');
        $this->removeColumn('dm_user_permission', 'created_at');
        $this->removeColumn('dm_user_permission', 'updated_at');
        
        $this->addColumn('dm_error', 'php_class', 'string', '127', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_layout', 'template', 'string', '255', array(
             'notnull' => '1',
             'default' => 'page',
             ));
        $this->addColumn('dm_mail_template', 'cc_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_mail_template', 'bcc_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_mail_template', 'reply_to_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_mail_template', 'sender_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_page', 'credentials', 'string', '255', array(
             'notnull' => '',
             ));
        $this->addColumn('dm_sent_mail', 'dm_mail_template_id', 'integer', '8', array(
             ));
        $this->addColumn('dm_sent_mail', 'subject', 'string', '5000', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_sent_mail', 'body', 'clob', '', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_sent_mail', 'from_email', 'string', '5000', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_sent_mail', 'to_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'cc_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'bcc_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'reply_to_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'sender_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'strategy', 'string', '255', array(
             ));
        $this->addColumn('dm_sent_mail', 'transport', 'string', '255', array(
             ));
        $this->addColumn('dm_sent_mail', 'culture', 'string', '16', array(
             ));
        $this->addColumn('dm_sent_mail', 'debug_string', 'clob', '', array(
             ));
        $this->addColumn('dm_page_translation', 'is_secure', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->dropTable('dm_lock');
        $this->dropTable('dm_auto_seo_translation');
        $this->dropTable('dm_mail_template_translation');
        $this->dropTable('dm_widget_translation');
        $this->addColumn('dm_auto_seo', 'slug', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_auto_seo', 'name', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_auto_seo', 'title', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_auto_seo', 'h1', 'string', '255', array(
             'notnull' => '',
             ));
        $this->addColumn('dm_auto_seo', 'description', 'string', '255', array(
             'notnull' => '',
             ));
        $this->addColumn('dm_auto_seo', 'keywords', 'string', '255', array(
             'notnull' => '',
             ));
        $this->addColumn('dm_auto_seo', 'strip_words', 'string', '10000', array(
             ));
        $this->addColumn('dm_error', 'klass', 'string', '127', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_group_permission', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_group_permission', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_mail_template', 'description', 'string', '5000', array(
             ));
        $this->addColumn('dm_mail_template', 'title', 'string', '5000', array(
             ));
        $this->addColumn('dm_mail_template', 'body', 'clob', '', array(
             ));
        $this->addColumn('dm_mail_template', 'from_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_mail_template', 'to_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_mail_template', 'is_html', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('dm_mail_template', 'is_active', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '1',
             ));
        $this->addColumn('dm_page', 'is_secure', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('dm_remember_key', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_sent_mail', 'name', 'string', '255', array(
             ));
        $this->addColumn('dm_sent_mail', 'header', 'string', '60000', array(
             ));
        $this->addColumn('dm_sent_mail', 'description', 'string', '60000', array(
             ));
        $this->addColumn('dm_user_group', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_user_group', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_user_permission', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_user_permission', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
//        $this->addColumn('dm_widget', 'value', 'string', '60000', array(
//             ));
        $this->removeColumn('dm_error', 'php_class');
        $this->removeColumn('dm_layout', 'template');
        $this->removeColumn('dm_mail_template', 'cc_email');
        $this->removeColumn('dm_mail_template', 'bcc_email');
        $this->removeColumn('dm_mail_template', 'reply_to_email');
        $this->removeColumn('dm_mail_template', 'sender_email');
        $this->removeColumn('dm_page', 'credentials');
        $this->removeColumn('dm_sent_mail', 'dm_mail_template_id');
        $this->removeColumn('dm_sent_mail', 'subject');
        $this->removeColumn('dm_sent_mail', 'body');
        $this->removeColumn('dm_sent_mail', 'from_email');
        $this->removeColumn('dm_sent_mail', 'to_email');
        $this->removeColumn('dm_sent_mail', 'cc_email');
        $this->removeColumn('dm_sent_mail', 'bcc_email');
        $this->removeColumn('dm_sent_mail', 'reply_to_email');
        $this->removeColumn('dm_sent_mail', 'sender_email');
        $this->removeColumn('dm_sent_mail', 'strategy');
        $this->removeColumn('dm_sent_mail', 'transport');
        $this->removeColumn('dm_sent_mail', 'culture');
        $this->removeColumn('dm_sent_mail', 'debug_string');
        $this->removeColumn('dm_page_translation', 'is_secure');
    }
}