<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {

        foreach(dmDb::pdo('SELECT * FROM dm_widget')->fetchAll(Doctrine::FETCH_ASSOC) as $widget)
        {
          dmDb::pdo(
            'INSERT INTO dm_widget_translation (id, lang, value) VALUES (?, ?, ?)',
            array($widget['id'], 'fr', $widget['value'])
          );
        }

        $this->removeColumn('dm_widget', 'value');
        
        $this->removeIndex('dm_area', 'layoutType', array(
             'fields' => 
             array(
              0 => 'dm_layout_id',
              1 => 'type',
             ),
             'type' => 'unique',
             ));
        $this->removeIndex('dm_auto_seo', 'moduleAction', array(
             'fields' => 
             array(
              0 => 'module',
              1 => 'action',
             ),
             'type' => 'unique',
             ));
        $this->removeIndex('dm_page_view', 'moduleAction', array(
             'fields' => 
             array(
              0 => 'module',
              1 => 'action',
             ),
             'type' => 'unique',
             ));
        $this->createForeignKey('dm_lock', 'dm_lock_user_id_dm_user_id', array(
             'name' => 'dm_lock_user_id_dm_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('dm_sent_mail', 'dm_sent_mail_dm_mail_template_id_dm_mail_template_id', array(
             'name' => 'dm_sent_mail_dm_mail_template_id_dm_mail_template_id',
             'local' => 'dm_mail_template_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_mail_template',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('dm_auto_seo_translation', 'dm_auto_seo_translation_id_dm_auto_seo_id', array(
             'name' => 'dm_auto_seo_translation_id_dm_auto_seo_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'dm_auto_seo',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('dm_mail_template_translation', 'dm_mail_template_translation_id_dm_mail_template_id', array(
             'name' => 'dm_mail_template_translation_id_dm_mail_template_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'dm_mail_template',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('dm_widget_translation', 'dm_widget_translation_id_dm_widget_id', array(
             'name' => 'dm_widget_translation_id_dm_widget_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'dm_widget',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('dm_auto_seo', 'dmAutoSeoModuleAction', array(
             'fields' => 
             array(
              0 => 'module',
              1 => 'action',
             ),
             'type' => 'unique',
             ));
        $this->addIndex('dm_lock', 'dm_lock_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('dm_page_view', 'dmPageViewModuleAction', array(
             'fields' => 
             array(
              0 => 'module',
              1 => 'action',
             ),
             'type' => 'unique',
             ));
        $this->addIndex('dm_sent_mail', 'dm_sent_mail_dm_mail_template_id', array(
             'fields' => 
             array(
              0 => 'dm_mail_template_id',
             ),
             ));
        $this->addIndex('dm_auto_seo_translation', 'dm_auto_seo_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('dm_mail_template_translation', 'dm_mail_template_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('dm_widget_translation', 'dm_widget_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->addIndex('dm_area', 'layoutType', array(
             'fields' => 
             array(
              0 => 'dm_layout_id',
              1 => 'type',
             ),
             'type' => 'unique',
             ));
        $this->addIndex('dm_auto_seo', 'moduleAction', array(
             'fields' => 
             array(
              0 => 'module',
              1 => 'action',
             ),
             'type' => 'unique',
             ));
        $this->addIndex('dm_page_view', 'moduleAction', array(
             'fields' => 
             array(
              0 => 'module',
              1 => 'action',
             ),
             'type' => 'unique',
             ));
        $this->dropForeignKey('dm_lock', 'dm_lock_user_id_dm_user_id');
        $this->dropForeignKey('dm_sent_mail', 'dm_sent_mail_dm_mail_template_id_dm_mail_template_id');
        $this->dropForeignKey('dm_auto_seo_translation', 'dm_auto_seo_translation_id_dm_auto_seo_id');
        $this->dropForeignKey('dm_mail_template_translation', 'dm_mail_template_translation_id_dm_mail_template_id');
        $this->dropForeignKey('dm_widget_translation', 'dm_widget_translation_id_dm_widget_id');
        $this->removeIndex('dm_auto_seo', 'dmAutoSeoModuleAction', array(
             'fields' => 
             array(
              0 => 'module',
              1 => 'action',
             ),
             'type' => 'unique',
             ));
        $this->removeIndex('dm_lock', 'dm_lock_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('dm_page_view', 'dmPageViewModuleAction', array(
             'fields' => 
             array(
              0 => 'module',
              1 => 'action',
             ),
             'type' => 'unique',
             ));
        $this->removeIndex('dm_sent_mail', 'dm_sent_mail_dm_mail_template_id', array(
             'fields' => 
             array(
              0 => 'dm_mail_template_id',
             ),
             ));
        $this->removeIndex('dm_auto_seo_translation', 'dm_auto_seo_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('dm_mail_template_translation', 'dm_mail_template_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('dm_widget_translation', 'dm_widget_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}