<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('rubrique', 'background_number', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('rubrique', 'background_number');
    }
}