generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: LienType
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: lien_type
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        is_active:
          label: Active
      list:
        display:
          - '=nom'
          - liens_list
          - is_active
          - created_at
          - updated_at
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
      filter:
        display:
          - nom
          - is_active
          - created_at
          - updated_at
      form:
        display:
          NONE: [nom, is_active]
        class: LienTypeAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: true
